language: rust
before_install:
- openssl aes-256-cbc -K $encrypted_1b1c25dbcf5c_key -iv $encrypted_1b1c25dbcf5c_iv
  -in scripts/id_rsa.enc -out scripts/id_rsa -d
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc --verbose
after_success: sh scripts/travis-doc-upload.sh
