language: rust
before_install:
- openssl aes-256-cbc -K $encrypted_1b1c25dbcf5c_key -iv $encrypted_1b1c25dbcf5c_iv
  -in scripts/id_rsa.enc -out scripts/id_rsa -d
script:
- cargo build --verbose
- cargo test --verbose
after_success:
- cargo doc
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh scripts/travis-doc-upload.sh; fi'
